# Generated by Django 5.0.2 on 2024-02-12 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название урока')),
                ('description', models.TextField(verbose_name='Описание урока')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью урока')),
                ('video_url', models.URLField(unique=True)),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название курса')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials_app.lesson')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
