# Generated by Django 5.0.2 on 2024-02-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_app', '0002_remove_course_lessons_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='owner',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Владелец'),
        ),
    ]
