# Generated by Django 4.2.5 on 2023-12-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temporary_password',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Temporary password'),
        ),
    ]
