# Generated by Django 4.2.5 on 2023-12-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_user_temporary_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
