# Generated by Django 5.0.2 on 2024-02-13 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_app', '0002_remove_course_lessons_lesson_course'),
        ('user_app', '0005_remove_user_country_user_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, verbose_name='Пользователь')),
                ('payment_date', models.DateField(verbose_name='Дата оплаты')),
                ('payment_sum', models.FloatField(verbose_name='Сумма платежа')),
                ('payment_type', models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Перевод')], verbose_name='Тип оплаты')),
                ('payed_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials_app.course')),
                ('payed_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials_app.lesson')),
            ],
            options={
                'verbose_name': 'Оплата пользователя',
                'verbose_name_plural': 'Оплаты пользователя',
            },
        ),
    ]
