# Generated by Django 5.0.2 on 2024-03-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_user_is_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Перевод')], max_length=5, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, unique=True, verbose_name='email'),
        ),
    ]
