# Generated by Django 4.0 on 2024-03-21 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('payment_sum', models.FloatField(default=1000, verbose_name='Сумма платежа')),
                ('payment_type', models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Перевод')], default='CASH', max_length=5, verbose_name='Тип оплаты')),
                ('payment_url', models.TextField(blank=True, null=True, verbose_name='URL оплаты')),
                ('payed_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials_app.course')),
                ('payed_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials_app.lesson')),
            ],
            options={
                'verbose_name': 'Оплата пользователя',
                'verbose_name_plural': 'Оплаты пользователя',
            },
        ),
    ]
